version: "3.8"

services:
  front:
    image: sermalenk/skypro-front:lesson-36
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
#    volumes:
#      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./src/static/:/apt/static/
  api:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
  migrations:
    build:
      context: .
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c "python3 manage.py migrate"
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5