# Generated by Django 4.1.4 on 2023-01-10 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0008_alter_goalcategory_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created',
        ),
        migrations.RemoveField(
            model_name='board',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='boardparticipant',
            name='created',
        ),
        migrations.RemoveField(
            model_name='boardparticipant',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='goalcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goalcategory',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='goalcomment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goalcomment',
            name='updated',
        ),
        migrations.AlterField(
            model_name='boardparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
