# Generated by Django 4.1.4 on 2023-01-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_remove_board_created_remove_board_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='board',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='boardparticipant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='boardparticipant',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='goal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='goal',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='goalcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='goalcategory',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='goalcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='goalcomment',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
