# Generated by Django 4.1.4 on 2023-01-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_alter_board_created_alter_board_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateTimeField(default=None, verbose_name='Срок выполнения'),
        ),
    ]
