# Generated by Django 4.1.4 on 2023-01-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_alter_goal_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateTimeField(verbose_name='Срок выполнения'),
        ),
    ]
