# Generated by Django 4.1.4 on 2023-01-10 21:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='tguser',
            name='telegram_user_id',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='tguser',
            name='telegram_username',
            field=models.CharField(default=None, max_length=32, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tguser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
