# Generated by Django 4.1.4 on 2023-01-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_tguser_telegram_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='telegram_chat_id',
            new_name='tg_chat_id',
        ),
        migrations.RenameField(
            model_name='tguser',
            old_name='telegram_user_id',
            new_name='tg_user_id',
        ),
        migrations.RenameField(
            model_name='tguser',
            old_name='telegram_username',
            new_name='tg_username',
        ),
    ]
