# Generated by Django 4.1.4 on 2023-01-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_rename_telegram_chat_id_tguser_tg_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_chat_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_user_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
